[2024-10-10T17:40:54.375+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-10T17:40:54.390+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LoadWebScraping.copy_data_to_temp_table manual__2024-10-10T17:40:50.574843+00:00 [queued]>
[2024-10-10T17:40:54.398+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LoadWebScraping.copy_data_to_temp_table manual__2024-10-10T17:40:50.574843+00:00 [queued]>
[2024-10-10T17:40:54.399+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-10T17:40:54.414+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): copy_data_to_temp_table> on 2024-10-10 17:40:50.574843+00:00
[2024-10-10T17:40:54.419+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=112) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-10T17:40:54.421+0000] {standard_task_runner.py:72} INFO - Started process 114 to run task
[2024-10-10T17:40:54.421+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'LoadWebScraping', 'copy_data_to_temp_table', 'manual__2024-10-10T17:40:50.574843+00:00', '--job-id', '1567', '--raw', '--subdir', 'DAGS_FOLDER/LoadWebScraping.py', '--cfg-path', '/tmp/tmp1fpa2sgd']
[2024-10-10T17:40:54.424+0000] {standard_task_runner.py:105} INFO - Job 1567: Subtask copy_data_to_temp_table
[2024-10-10T17:40:54.471+0000] {task_command.py:467} INFO - Running <TaskInstance: LoadWebScraping.copy_data_to_temp_table manual__2024-10-10T17:40:50.574843+00:00 [running]> on host 97b4e38b3eb9
[2024-10-10T17:40:54.804+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='LoadWebScraping' AIRFLOW_CTX_TASK_ID='copy_data_to_temp_table' AIRFLOW_CTX_EXECUTION_DATE='2024-10-10T17:40:50.574843+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-10T17:40:50.574843+00:00'
[2024-10-10T17:40:54.805+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-10T17:40:54.819+0000] {sql.py:266} INFO - Executing: 
        COPY tb_dim_site (id_site, name_site)
        FROM '/opt/***/datalake/silverzone/pichau_2024-10-09/dim_site.csv/part-00000-104d56a6-9023-4092-88cd-2ba9181765ee-c000.csv'
        DELIMITER ','
        CSV HEADER;
        
[2024-10-10T17:40:54.827+0000] {base.py:84} INFO - Retrieving connection 'postgres-***'
[2024-10-10T17:40:54.835+0000] {base.py:84} INFO - Retrieving connection 'postgres-***'
[2024-10-10T17:40:54.844+0000] {sql.py:509} INFO - Running statement: 
        COPY tb_dim_site (id_site, name_site)
        FROM '/opt/***/datalake/silverzone/pichau_2024-10-09/dim_site.csv/part-00000-104d56a6-9023-4092-88cd-2ba9181765ee-c000.csv'
        DELIMITER ','
        CSV HEADER;
        , parameters: None
[2024-10-10T17:40:54.903+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/opt/***/datalake/silverzone/pichau_2024-10-09/dim_site.csv/part-00000-104d56a6-9023-4092-88cd-2ba9181765ee-c000.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2024-10-10T17:40:54.913+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=LoadWebScraping, task_id=copy_data_to_temp_table, run_id=manual__2024-10-10T17:40:50.574843+00:00, execution_date=20241010T174050, start_date=20241010T174054, end_date=20241010T174054
[2024-10-10T17:40:54.935+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-10T17:40:54.936+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1567 for task copy_data_to_temp_table (could not open file "/opt/***/datalake/silverzone/pichau_2024-10-09/dim_site.csv/part-00000-104d56a6-9023-4092-88cd-2ba9181765ee-c000.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 114)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/opt/***/datalake/silverzone/pichau_2024-10-09/dim_site.csv/part-00000-104d56a6-9023-4092-88cd-2ba9181765ee-c000.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2024-10-10T17:40:54.960+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-10T17:40:54.976+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-10T17:40:54.982+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
