[2024-10-05T14:40:44.487+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-05T14:40:44.504+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pichau_pipeline.pichau_tasks.Web_Extraction_pichau manual__2024-10-05T14:40:41.558029+00:00 [queued]>
[2024-10-05T14:40:44.513+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pichau_pipeline.pichau_tasks.Web_Extraction_pichau manual__2024-10-05T14:40:41.558029+00:00 [queued]>
[2024-10-05T14:40:44.514+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-05T14:40:44.530+0000] {taskinstance.py:2888} INFO - Executing <Task(OperatorSiteA): pichau_tasks.Web_Extraction_pichau> on 2024-10-05 14:40:41.558029+00:00
[2024-10-05T14:40:44.534+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4538) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-05T14:40:44.536+0000] {standard_task_runner.py:72} INFO - Started process 4539 to run task
[2024-10-05T14:40:44.536+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pichau_pipeline', 'pichau_tasks.Web_Extraction_pichau', 'manual__2024-10-05T14:40:41.558029+00:00', '--job-id', '1189', '--raw', '--subdir', 'DAGS_FOLDER/DagWebScraping.py', '--cfg-path', '/tmp/tmprcwoq_70']
[2024-10-05T14:40:44.539+0000] {standard_task_runner.py:105} INFO - Job 1189: Subtask pichau_tasks.Web_Extraction_pichau
[2024-10-05T14:40:44.582+0000] {task_command.py:467} INFO - Running <TaskInstance: pichau_pipeline.pichau_tasks.Web_Extraction_pichau manual__2024-10-05T14:40:41.558029+00:00 [running]> on host e823e678f418
[2024-10-05T14:40:44.653+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pichau_pipeline' AIRFLOW_CTX_TASK_ID='pichau_tasks.Web_Extraction_pichau' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T14:40:41.558029+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-05T14:40:41.558029+00:00'
[2024-10-05T14:40:44.654+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-05T14:43:05.897+0000] {logging_mixin.py:190} INFO - Create_Container_Raw_pichau
[2024-10-05T14:43:05.907+0000] {logging_mixin.py:190} INFO - None
[2024-10-05T14:43:05.909+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorSiteA.py", line 98, in execute
    self.SaveFile(context)
  File "/opt/airflow/operators/OperatorSiteBase.py", line 80, in SaveFile
    filepath = os.path.join(path, 'data.json')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-10-05T14:43:05.923+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=pichau_pipeline, task_id=pichau_tasks.Web_Extraction_pichau, run_id=manual__2024-10-05T14:40:41.558029+00:00, execution_date=20241005T144041, start_date=20241005T144044, end_date=20241005T144305
[2024-10-05T14:43:05.938+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-05T14:43:05.939+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1189 for task pichau_tasks.Web_Extraction_pichau (expected str, bytes or os.PathLike object, not NoneType; 4539)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/OperatorSiteA.py", line 98, in execute
    self.SaveFile(context)
  File "/opt/airflow/operators/OperatorSiteBase.py", line 80, in SaveFile
    filepath = os.path.join(path, 'data.json')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-10-05T14:43:05.970+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-05T14:43:05.997+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-05T14:43:06.019+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
